### ISSUE TITLE
Incompatibility with pyquil 2.0.0

### ISSUE THREAD

**Issue by peterse** [rigetticomputing/grove#184]
pyquil 2.0.0 offers a local QVM wrapped in the `QuantumComputer` class, but this is not compatible with calls to a `VQE` object. Trying to pass the QuantumComputer object to the `expectation()` method of `VQE` results in the error:

`AttributeError: 'QuantumComputer' object has no attribute 'expectation'`

Is there any way to run VQE on a local QVM object? If not, are there plans for grove to be updated to be compatible with pyquil 2.0?

**Comment by lcapelluto** [comment]
Hi @peterse, thanks for opening this issue! There are indeed plans for Grove to be updated soon.

The `QVM` object within `QuantumComputer.qam` no longer has the method `expectation()`. This was motivated by the desire to make `QVM` and `QPU` as interchangeable as possible -- we want users to be able to debug their programs completely before booking QPU time. 

Those "non-physical" methods still exist as part of our [`WavefunctionSimulator`](https://pyquil.readthedocs.io/en/latest/wavefunction_simulator.html). I haven't worked much in Grove myself, but from a quick glance it seems much of `VQE` will be rewritten to use the `WavefunctionSimulator`.

So, to answer the first part of your question... as it is currently, VQE will not work; it still needs to be migrated to work with pyQuil 2.0. The rework will make use of both a local QVM object (for `.run`) _and_ the WaveformSimulator (for `.wavefunction`, `.expectation`). If you don't want to wait while we work on it, and you are interested in migrating it yourself, check out the [migration guide](https://pyquil.readthedocs.io/en/latest/migration.html). (The guide will also be updated soon.) We'll be around to respond to more issues if you have trouble migrating. (cc @mpharrigan)
